name: firebase_tutorial
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  firebase_database: ^10.3.8
  flutter:
    sdk: flutter
   # 状態管理関連
  flutter_riverpod: 2.4.9
  riverpod_annotation: 2.3.3
  freezed: 2.4.5
  freezed_annotation: 2.4.1
  json_serializable: 6.7.1
  json_annotation: 4.8.1

  # 遷移関連
  routemaster: ^1.0.1
  build_runner: ^2.4.7
  cloud_firestore: ^4.13.5
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.2
  google_sign_in: ^6.1.6

  http: ^1.1.0
  riverpod_generator: ^2.3.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
